import type { RemediationToolName } from '../../api/src/services/documentModel.ts'

/** Mirrors `RemediationToolName` in documentModel.ts for runtime validation. */
export const REMEDIATION_TOOL_NAMES = [
  'ocr_scanned_pdf',
  'adobe_accessibility_check',
  'adobe_auto_tag',
  'get_document_metadata',
  'set_document_title',
  'set_document_language',
  'set_pdfua_identification',
  'normalize_document_metadata',
  'repair_structure_conformance',
  'repair_malformed_bdc_operators',
  'repair_note_tag_ids',
  'repair_native_marked_content_refs',
  'repair_native_link_structure',
  'tag_unowned_annotations',
  'repair_bootstrapped_chart_content_refs',
  'repair_native_figure_semantics',
  'repair_other_elements_alt_text',
  'repair_native_table_headers',
  'repair_native_reading_order',
  'repair_font_unicode_maps',
  'repair_type1_font_unicode_maps',
  'repair_truetype_encoding_differences',
  'repair_annotation_alt_text',
  'set_tabs_all_annotated_pages',
  'substitute_legacy_fonts_in_place',
  'finalize_substituted_font_conformance',
  'repair_cidset_consistency',
  'set_page_tabs',
  'normalize_annotation_tab_order',
  'list_bookmarks',
  'create_bookmark',
  'replace_bookmarks_from_headings',
  'list_links',
  'set_link_annotation_contents',
  'repair_cid_symbol_font_maps',
  'embed_missing_fonts_in_place',
  'embed_missing_fonts_for_page_content',
  'update_link_destination',
  'update_link_visible_text',
  'list_figures',
  'set_figure_alt_text',
  'retag_as_figure_and_set_alt',
  'mark_figure_decorative',
  'list_form_fields',
  'set_form_field_label',
  'set_form_field_tooltip',
  'inspect_tag_tree',
  'list_heading_candidates',
  'list_table_candidates',
  'inspect_reading_order',
  'bootstrap_struct_tree',
  'create_heading_from_candidate',
  'normalize_heading_hierarchy',
  'normalize_nested_figure_containers',
  'retag_node',
  'create_heading_tag',
  'set_table_header_cells',
  'move_tag_in_reading_order',
  'reorder_structure_children',
  'rewrite_link_visible_text',
  'mark_content_artifact',
  'artifact_nonsemantic_page_elements',
  'save_working_pdf',
] as const satisfies readonly RemediationToolName[]

export const REMEDIATION_TOOL_NAME_SET = new Set<string>(REMEDIATION_TOOL_NAMES)

export function isRemediationToolName(name: string): name is RemediationToolName {
  return REMEDIATION_TOOL_NAME_SET.has(name)
}
